CLASS zcl_01_exec_logali_c367_cv DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES if_oo_adt_classrun.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_01_exec_logali_c367_cv IMPLEMENTATION.
  METHOD if_oo_adt_classrun~main.


  ENDMETHOD.

ENDCLASS.
