CLASS zcl_12_airplane_lgl_c367_cv DEFINITION ABSTRACT
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS:
      airplane_type ABSTRACT
        RETURNING VALUE(rv_airplane_type) TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_12_airplane_lgl_c367_cv IMPLEMENTATION.
ENDCLASS.
