CLASS zcl_06_storage_lgl_c367_cv DEFINITION INHERITING FROM zcl_05_plant_lgl_c367_cv
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_06_storage_lgl_c367_cv IMPLEMENTATION.
ENDCLASS.
