CLASS zcl_10_eu_citizen_lgl_c367_cv DEFINITION INHERITING FROM zcl_09_citizen_lgl_c367_cv
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_10_eu_citizen_lgl_c367_cv IMPLEMENTATION.

ENDCLASS.
