CLASS zcl_22_vat_ind_log_c367_cv DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    DATA: vat_ind TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_22_vat_ind_log_c367_cv IMPLEMENTATION.
ENDCLASS.
