CLASS zcl_plant_c367_cv DEFINITION INHERITING FROM zcl_company_c367_cv
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_plant_c367_cv IMPLEMENTATION.
ENDCLASS.
