CLASS zcl_19_honda_lgl_c367_cv DEFINITION ABSTRACT INHERITING FROM zcl_18_moto_lgl_c367_cv
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

  PROTECTED SECTION.
    METHODS: set_model ABSTRACT EXPORTING model TYPE string.

  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_19_honda_lgl_c367_cv IMPLEMENTATION.
ENDCLASS.
