CLASS zcl_33_record_cntr_lgl_c367_cv DEFINITION INHERITING FROM zcl_32_constr_cntr_lgl_c367_cv
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_33_record_cntr_lgl_c367_cv IMPLEMENTATION.
ENDCLASS.
