CLASS zcl_29_keyboard_lgl_c367_cv DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    DATA: keyboard_type TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_29_keyboard_lgl_c367_cv IMPLEMENTATION.
ENDCLASS.
