CLASS zcl_31_vat_ind_lgl_c367_cv DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    DATA: vat_ind TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_31_vat_ind_lgl_c367_cv IMPLEMENTATION.
ENDCLASS.
